apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test
  region: us-east-1
iam:
  withOIDC: true
# eksctl/examples/13-iamserviceaccounts.yaml
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
# eksctl/examples/25-addons.yaml
addons:
- name: vpc-cni
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
nodeGroups:
  - name: test-ng
    instanceType: m5.large
    desiredCapacity: 2
    privateNetworking: true
#    iam:
#      withAddonPolicies:
#        albIngress: true
#        cloudWatch: true
vpc:
#  securityGroup: "sg-02fd2a403d91711cb"
  subnets:
    private:
      us-east-1a:
        id: "subnet-069dcadb14a6aed63"
      us-east-1b:
        id: "subnet-0bf0e7ac1e71923de"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
